# Generated by Django 4.1 on 2022-08-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_country_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_from', models.CharField(max_length=50)),
                ('arrival_at', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
