# Generated by Django 4.1 on 2022-08-20 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_checkrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkrequest',
            name='check_time',
            field=models.TimeField(default=datetime.time),
            preserve_default=False,
        ),
    ]
