# Generated by Django 4.1 on 2022-08-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_checkrequest_check_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_from', models.CharField(max_length=50)),
                ('arrival_at', models.CharField(max_length=50)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='CheckRequest',
        ),
    ]
