# Generated by Django 4.1 on 2022-08-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_connection_delete_checkrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Station',
        ),
    ]
