# Generated by Django 4.1.1 on 2022-09-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_reminder_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='time',
            new_name='departure_time',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='date',
            new_name='departure_date',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='time',
            new_name='reminder_time',
        ),
    ]
